name: obfuscate 
base: core22 
version: '0.0.9'  
adopt-info: obfuscate
license: GPL-3.0+
issues: https://github.com/soumyaDghosh/obfuscate-snap/issues
source-code: https://gitlab.gnome.org/World/obfuscate
website: https://github.com/soumyaDghosh/obfuscate-snap
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

grade: stable 
confinement: strict 
compression: lzo

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: ''

  obfuscate:
    after: [rustup]
    plugin: meson
    source: https://gitlab.gnome.org/World/obfuscate.git
    source-depth: 1
    source-tag: '0.0.10'
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT 
    meson-parameters:
      - --prefix=/snap/obfuscate/current/usr
    override-pull: |
      craftctl default
      sed -i 's|https://gitlab.gnome.org/World/obfuscate/|https://github.com/soumyaDghosh/obfuscate-snap/|g' ${CRAFT_PART_SRC}/src/application.rs
    organize:
      snap/obfuscate/current: .
    parse-info:
      - usr/share/metainfo/com.belmoussaoui.Obfuscate.metainfo.xml
    prime:
      - -snap/obfuscate

slots:
  obfuscate:
    interface: dbus
    bus: session
    name: com.belmoussaoui.Obfuscate

apps:
  obfuscate:
    command: usr/bin/obfuscate
    extensions: [gnome]
    common-id: com.belmoussaoui.Obfuscate
    desktop: usr/share/applications/com.belmoussaoui.Obfuscate.desktop
