name: obfuscate 
base: core24 
adopt-info: obfuscate
issues: https://github.com/soumyaDghosh/obfuscate-snap/issues
grade: stable 
confinement: strict 
compression: lzo
platforms:
  amd64:
  arm64:
  armhf:

parts:
  rustup:
    plugin: rust
    source: .
    rust-channel: "1.76"
    override-build: ""
    override-prime: ""

  obfuscate:
    after: [rustup]
    plugin: meson
    source: https://gitlab.gnome.org/World/obfuscate.git
    source-depth: 1
    source-tag: '0.0.10'
    build-environment:
      - PATH: ${HOME}/.cargo/bin:${PATH}
    meson-parameters:
      - --prefix=/snap/obfuscate/current/usr
    organize:
      snap/obfuscate/current: .
    parse-info:
      - usr/share/metainfo/com.belmoussaoui.Obfuscate.metainfo.xml
    prime:
      - -snap/obfuscate

slots:
  obfuscate:
    interface: dbus
    bus: session
    name: com.belmoussaoui.Obfuscate

apps:
  obfuscate:
    command: usr/bin/obfuscate
    extensions: [gnome]
    common-id: com.belmoussaoui.Obfuscate
    desktop: usr/share/applications/com.belmoussaoui.Obfuscate.desktop
