name: obfuscate # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.0.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo
parts:
  libadwaita:
    after: [rustup]
    source: https://gitlab.gnome.org/GNOME/libadwaita.git
    source-tag: '1.3.1'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dintrospection=enabled
      - -Dvapi=true
      - -Dtests=false
      - -Dexamples=false
    build-packages:
      - sassc
    override-pull: |
      craftctl default
      sed -e 's/-W\(format-nonliteral\)\b/-Wno-\1/g' -i meson.build
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  obfuscate:
    after: [rustup, libadwaita]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/World/obfuscate.git
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - -Dprofile=development
    override-stage: |
      craftctl default
      sed 's|Icon=com.belmoussaoui.Obfuscate|Icon=usr/share/icons/hicolor/scalable/apps/com.belmoussaoui.Obfuscate.svg|' $CRAFT_PART_INSTALL/usr/share/applications/com.belmoussaoui.Obfuscate.desktop
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - obfuscate
      - libadwaita
      - rustup
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gnome-42-2204-sdk
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gnome-42-2204-sdk" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  obfuscate:
    command: usr/bin/obfuscate
    extensions: [gnome]
    common-id: com.belmoussaoui.Obfuscate
    desktop: usr/share/applications/com.belmoussaoui.Obfuscate.desktop
    plugs:
      - home
